<a href="https://colab.research.google.com/github/PaiSuryaDarshan/ML_Prerequisites_TNSV2/blob/main/TNSV2_2024_09_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matricies

In [21]:
L = [[1,2],[3,4]]

In [22]:
# rows
L[0]

[1, 2]

In [23]:
# [rows][cols]
L[0][1]

2

In [24]:
# notice the formatting appears like a matrix

import numpy as np
A = np.array(L)
A

array([[1, 2],
       [3, 4]])

In [25]:
# similar to list but allows for more accesible collection

In [26]:
# Select row 0

A[0]

array([1, 2])

In [27]:
# Select row 0

A[0][1]

2

In [28]:
# Select row (Alt method)

A[0,1]

2

In [29]:
# Lists CANNOT be parsed to show only cols

L[:][0]

[1, 2]

## This is where np becomes POWERFUL


In [30]:
# Select columns (':' stands for select all rows)
A[:,1]

array([2, 4])

In [32]:
# Transpose (swap rows and columns)
A.T

array([[1, 3],
       [2, 4]])

In [33]:
 np.exp(A)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [35]:
# numpy being smart,
# can take operations carried out on a list and return an array

np.exp(L) # Takes list, operates and returns array

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [36]:
np.sqrt(L)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

## Matrix Multiplication

In [97]:
A = np.array([[1,2],[3,4]])
B = np.array([[1,2,3],[4,5,6]])
C = np.array([[1,2]])
D = np.array([[3,4]])

A

array([[1, 2],
       [3, 4]])

In [98]:
B

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
A.dot(B)

array([[ 9, 12, 15],
       [19, 26, 33]])

In [100]:
C.shape

(1, 2)

In [101]:
B.shape

(2, 3)

In [102]:
C.dot(B)

array([[ 9, 12, 15]])

In [103]:
 A.shape

(2, 2)

In [109]:
B.dot(A)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [110]:
# Finding the matrix determinant

np.linalg.det(A)

-2.0000000000000004

In [111]:
# matrix determinants can only exist for square matricies

np.linalg.det(B)

LinAlgError: Last 2 dimensions of the array must be square

In [ ]:
# linalg.inv()
# linalg.det()
# linalg.eig() (eigen values and eigen vectors)