<a href="https://colab.research.google.com/github/PaiSuryaDarshan/ML_Prerequisites_TNSV2/blob/main/TNSV2_2024_08_31.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

In [17]:
l = [1,2,3]

In [18]:
A = np.array(l)

In [19]:
for i in l:
    print(i)

1
2
3


In [20]:
for i in A:
    print(i)

1
2
3


In [21]:
l.append(4)

In [22]:
l

[1, 2, 3, 4]

In [23]:
A.append(4)

# Arrays have fixed size

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [24]:
l += [5]
l

[1, 2, 3, 4, 5]

In [25]:
# This is called broadcasting in numpy, illegal mathematical operation,
# BUT numpy creats a list with the same input which matches the original list

A += np.array([4])
A

array([5, 6, 7])

In [26]:
A += np.array([6,5,4])
A

array([11, 11, 11])

How Arrays make arithemetics simpler

In [32]:
LIST = [2,4,5]
A = np.array(LIST)

In [33]:
# To square a list (element wise)

New_LIST = []
for i in LIST:
    New_LIST.append(i**2)

New_LIST

[4, 16, 25]

In [34]:
# To square an array (element-wise)

A**2

array([ 4, 16, 25])

In [35]:
np.sqrt(A)

array([1.41421356, 2.        , 2.23606798])

In [36]:
np.log(A)

array([0.69314718, 1.38629436, 1.60943791])

# Dot Product

In [43]:
# let's make two template arrays

a = np.array([1,2])
b = np.array([3,4])

## Alternate work arounds

In [44]:
# going by definition
dot = 0
for e,f in zip(a,b):
    dot += e*f

dot # (1*3) + (2*4)

11

In [45]:
dot = 0
for i in range(len(a)):
    dot += a[i]*b[i]

dot

11

In [49]:
# alternate method using np

dot = (a*b)
sum_of_dot = dot.sum()
sum_of_dot

11

In [51]:
# or another alternate

np.sum(a*b)

11

## Real way(s) to do it

In [54]:
# HOWEVER, THIS IS THE REAL WAY TO DO IT

np.dot(a,b)

11

In [55]:
# Since dot is also an instance function
a.dot(b)

11

In [56]:
# Later numpy version uses @ symbol to describe np.dot
a@b

11

## Dot product (alternative DEFINITION)
from linear Algebra

It provides us the ability to find Angle between 2 vectors from Cosine...

## Finding Magnitude

In [58]:
# Alt workaround

a_mag = np.sqrt((a*a).sum())
a_mag

2.23606797749979

In [64]:
# Real Method
# use module 'linalg" within numpy.
# Provides several tools to carry out linear applications on arrays

a_mag = np.linalg.norm(a)
b_mag = np.linalg.norm(b)

a_mag, b_mag

(2.23606797749979, 5.0)

In [67]:
cosangle = a.dot(b)/ (a_mag * b_mag)
cosangle

0.9838699100999074

In [68]:
angle = np.arccos(cosangle)
angle # OUTPUTS in radians NOT degrees

0.17985349979247847

In [70]:
# to convert angle to degrees
angle_degrees = np.degrees(angle)
angle_degrees

10.304846468766044